apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https-node
    port: 443
    targetPort: 8443
    nodePort: 32045
    protocol: TCP
  - name: http-node
    nodePort: 32044
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.65.181.16